<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title>Exemplo - iCalendar com Zend Framework</title>
	</head>
	<body>
		<p>Problably you've found it on my github - https://github.com/adlermedrado</p>
		<p>To see the example running, look at exampleController</p>
		<p>Hope it helps ya!</p>
		<p>Best,<br />Adler Medrado - http://adlermedrado.com.br</p>
	</body>
</html>